<?php

/**
 * @file
 * Contains bcalc.module.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\node\NodeInterface;


/**
 * Implements hook_theme().
 */
function bcalc_theme() {
  return [
    'month-summary' => [
      'variables' => [
        'tabs' => NULL,
        'tabscontent' => NULL,
      ],
    ],
    'year-summary' => [
      'variables' => [
        'yearly_summary_chart' => NULL,
        'yearly_summary_averages' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_form_alter().
 */
function bcalc_form_alter(&$form, FormStateInterface $form_state) {
  if ($form['#form_id'] == 'taxonomy_term_category_form') {
    #$form['relations']['parent']['#multiple'] = false;
    $form['relations']['parent']['#attributes'] = ['style' => 'height: 400px;'];
    $form['relations']['#open'] = TRUE;
    $form['relations']['weight']['#access'] = FALSE;
  }
}

/**
 * Implements template_preprocess_page
 *
 * @param $variables
 */
function bcalc_preprocess_charts_api_example(&$variables) {
  $plugin_manager = \Drupal::service('plugin.manager.charts');
  $plugin = $plugin_manager->createInstance($variables['library']);
  $plugin->buildVariables($variables['options'], $variables['categories'], $variables['seriesData'], [], $variables, $variables['id']);
}

/**
 * Implements hook_entity_update().
 */
function bcalc_node_update(NodeInterface $node) {
  if ($node->getType() == 'line_item') {
    $cache = \Drupal::cache();
    //delete cached data for that month
    $yearmonth = substr($node->get('field_trans_date')->value, 0, 7);
    $cid = 'monthlystats.' . str_replace('-', '', $yearmonth)
      . '.income.' . \Drupal::currentUser()->id();
    if ($cache->get($cid)) {

      $cache->delete('last12.summary.stats.'
        . $yearmonth . '.'
        . \Drupal::currentUser()->id());
      $cache->delete('last6.summary.stats.'
        . $yearmonth . '.'
        . \Drupal::currentUser()->id());

      $cache->delete($cid);
      $cache->delete(str_replace('income', 'spending', $cid));

      $year = substr($yearmonth, 0, 4);
      $cache_id = 'yearlystats.' . $year . \Drupal::currentUser()->id();
      $cache->delete($cache_id);
    }
  }
}

/**
 * Implements hook_entity_insert().
 */
function bcalc_node_insert(NodeInterface $node) {
  if ($node->getType() == 'line_item') {
    $cache = \Drupal::cache();
    //delete cached data for that month
    $yearmonth = substr($node->get('field_trans_date')->value, 0, 7);
    $cid = 'monthlystats.' . str_replace('-', '', $yearmonth)
      . '.income.' . \Drupal::currentUser()->id();
    if ($cache->get($cid)) {
      $cache->delete('last12.summary.stats.'
        . $yearmonth . '.'
        . \Drupal::currentUser()->id());

      $cache->delete('last6.summary.stats.'
        . $yearmonth . '.'
        . \Drupal::currentUser()->id());

      $cache->delete($cid);
      $cache->delete(str_replace('income', 'spending', $cid));

      $year = substr($yearmonth, 0, 4);
      $cache_id = 'yearlystats.' . $year . \Drupal::currentUser()->id();
      $cache->delete($cache_id);
    }
  }
}