<?php

/**
 * @file
 * Contains bcalc.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\node\NodeInterface;

/**
 * Implements hook_help().
 */
function bcalc_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the bcalc module.
    case 'help.page.bcalc':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Family Budget Calculator') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function bcalc_theme() {
  return [
    'bcalc' => [
      'render element' => 'children',
    ],
    'homepage' => [
      'variables' => [
        'tabs' => NULL,
        'tabscontent' => NULL,
        'yearly_summary_chart' => NULL,
      ],
    ],
  ];
}

/**
 * Implements hook_form_alter().
 */
function bcalc_form_alter(&$form, FormStateInterface $form_state) {
  if ($form['#form_id'] == 'taxonomy_term_category_form') {
    #$form['relations']['parent']['#multiple'] = false;
    $form['relations']['parent']['#attributes'] = ['style' => 'height: 400px;'];
    $form['relations']['#open'] = TRUE;
    $form['relations']['weight']['#access'] = FALSE;
  }
}

/**
 * Implements template_preprocess_page
 *
 * @param $variables
 */
function bcalc_preprocess_charts_api_example(&$variables) {
  $plugin_manager = \Drupal::service('plugin.manager.charts');
  $plugin = $plugin_manager->createInstance($variables['library']);
  $plugin->buildVariables($variables['options'], $variables['categories'], $variables['seriesData'], [], $variables, $variables['id']);
}

/**
 * Implements hook_entity_update().
 */
function bcalc_node_update(NodeInterface $node) {
  if ($node->getType() == 'line_item') {
    //delete cached data for that month
    $yearmonth = substr($node->get('field_trans_date')->value, 0, 7);
    $cid = 'monthlystats.' . str_replace('-', '', $yearmonth);
    \Drupal::cache()->delete($cid);
  }
}

/**
 * Implements hook_entity_insert().
 */
function bcalc_node_insert(NodeInterface $node) {
  if ($node->getType() == 'line_item') {
    //delete cached data for that month
    $yearmonth = substr($node->get('field_trans_date')->value, 0, 7);
    $cid = 'monthlystats.' . str_replace('-', '', $yearmonth);
    \Drupal::cache()->delete($cid);
  }
}