<?php
/**
 * @file
 * Bootstrap sub-theme.
 *
 * Place your custom PHP code in this file.
 */

/**
 * Implements hook_preprocess_HOOK() for HTML document templates.
 *
 * Adds body classes if certain regions have content.
 */
function bcalc_subtheme_preprocess_html(&$variables) {
  // Add information about the number of sidebars.
  if (\Drupal::service('path.matcher')->isFrontPage() && !empty($variables['page']['sidebar_first'])) {
    unset($variables['page']['sidebar_first']);
  }
}